[package]
name = "rust-test"
version = "0.1.0"
authors = ["Conor Farrell <conorf50@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.4"
rand = "0.7.3"